function [predictedLevel, confidenceScore] = predictDR_CNN(imagePath)
% predictDR_CNN - Evaluates an image using the trained ResNet-50 model.
%
% This function loads the trained weights generated by trainDR_CNN.m.
% If the model has not been trained yet (the .mat file is missing), 
% it will output a simulated score to prevent the pipeline from crashing 
% during demonstrations.
%
% Inputs:
%   imagePath - Path to the preprocessed fundus image.
%
% Outputs:
%   predictedLevel - Integer (0 to 4) representing severity.
%   confidenceScore - Double (0.0 to 1.0) representing softmax probability.

    persistent trainedNet
    
    % Define the path where the trained model should be saved
    modelPath = fullfile(fileparts(mfilename('fullpath')), '..', 'ai_training', 'trained_DR_ResNet.mat');
    
    % Check if the real model exists
    if exist(modelPath, 'file')
        % Load the model only once to save time
        if isempty(trainedNet)
            disp('Loading trained ResNet-50 model from disk...');
            modelData = load(modelPath, 'trainedNet');
            trainedNet = modelData.trainedNet;
        end
        
        % Read and resize the image for ResNet-50 (224x224)
        img = imread(imagePath);
        if size(img, 3) == 1
            img = cat(3, img, img, img); % Convert grayscale to RGB if needed
        end
        imgResized = imresize(img, [224 224]);
        
        % Perform Inference
        [predClass, scores] = classify(trainedNet, imgResized);
        
        % Convert categorical class to integer level (assuming classes are '0','1','2','3','4')
        predictedLevel = str2double(char(predClass));
        confidenceScore = max(scores);
        
    else
        % ================================================================
        % MOCK MODE (For Demonstration before training is complete)
        % ================================================================
        warning('trained_DR_ResNet.mat not found. Using MOCK AI prediction for demonstration purposes.');
        
        % For demonstration, we simulate a low confidence prediction to trigger the fail-safe
        % or a high confidence prediction depending on the image name.
        % Let's randomly simulate a score, or set a fixed one for predictability in demos.
        
        if contains(imagePath, 'IDRiD_12')
            % Simulate AI failing/being uncertain on this specific image
            predictedLevel = 2;
            confidenceScore = 0.65; % < 0.75 triggers fail-safe
        else
            % Simulate a confident prediction
            predictedLevel = 1;
            confidenceScore = 0.92;
        end
    end
end
